apiVersion: v1
kind: ConfigMap
metadata:
  name: logging-config
  namespace: rag-system
data:
  config.toml: |
    [logger]
    level = "debug"
    messageFormat = "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
    
    [client]
    showErrorDetails = true
    toolbarMode = "developer"