apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  namespace: {{ .Values.global.namespace }}
type: Opaque
data:
  username: {{ .Values.postgres.credentials.username | b64enc }}
  password: {{ .Values.postgres.credentials.password | b64enc }}