{{- if .Values.frontend.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: {{ .Values.global.namespace }}
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8501
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: {{ .Values.global.namespace }}
spec:
  replicas: {{ .Values.frontend.replicas }}
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: {{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}
        imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
        ports:
        - containerPort: 8501
        env:
        - name: EMBEDDING_SERVICE_URL
          value: "http://embedding-service.{{ .Values.global.namespace }}.svc.cluster.local"
        - name: RAG_SERVICE_URL
          value: "http://rag-service.{{ .Values.global.namespace }}.svc.cluster.local"
        - name: ENVIRONMENT
          value: {{ .Values.global.environment }}
        - name: LOG_LEVEL
          value: "DEBUG"
        resources:
{{ toYaml .Values.frontend.resources | indent 10 }}
        volumeMounts:
        - name: logging-config
          mountPath: /app/.streamlit
          readOnly: true
      volumes:
      - name: logging-config
        configMap:
          name: logging-config
{{- end }}